export const MONITOR_LEAKS_GET_LEAKS_INFOS_BEGIN = 'MONITOR_LEAKS_GET_LEAKS_INFOS_BEGIN';
export const MONITOR_LEAKS_GET_LEAKS_INFOS_SUCCESS = 'MONITOR_LEAKS_GET_LEAKS_INFOS_SUCCESS';
export const MONITOR_LEAKS_GET_LEAKS_INFOS_FAILURE = 'MONITOR_LEAKS_GET_LEAKS_INFOS_FAILURE';

export const MONITOR_LEAKS_FIX_LEAKS_INFO_BEGIN = 'MONITOR_LEAKS_FIX_LEAKS_INFO_BEGIN';
export const MONITOR_LEAKS_FIX_LEAKS_INFO_SUCCESS = 'MONITOR_LEAKS_FIX_LEAKS_INFO_SUCCESS';
export const MONITOR_LEAKS_FIX_LEAKS_INFO_FAILURE = 'MONITOR_LEAKS_FIX_LEAKS_INFO_FAILURE';

export const MONITOR_LEAKS_ADD_LEAK_COMMENT_BEGIN = 'MONITOR_LEAKS_ADD_LEAK_COMMENT_BEGIN';
export const MONITOR_LEAKS_ADD_LEAK_COMMENT_SUCCESS = 'MONITOR_LEAKS_ADD_LEAK_COMMENT_SUCCESS';
export const MONITOR_LEAKS_ADD_LEAK_COMMENT_FAILURE = 'MONITOR_LEAKS_ADD_LEAK_COMMENT_FAILURE';

export const MONITOR_LEAKS_GET_APPS_BEGIN = 'MONITOR_LEAKS_GET_APPS_BEGIN';
export const MONITOR_LEAKS_GET_APPS_SUCCESS = 'MONITOR_LEAKS_GET_APPS_SUCCESS';
export const MONITOR_LEAKS_GET_APPS_FAILURE = 'MONITOR_LEAKS_GET_APPS_FAILURE';
