export const USER_GET_USER_INFO_BEGIN = 'USER_GET_USER_INFO_BEGIN';
export const USER_GET_USER_INFO_SUCCESS = 'USER_GET_USER_INFO_SUCCESS';
export const USER_GET_USER_INFO_FAILURE = 'USER_GET_USER_INFO_FAILURE';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
