export const WEBSOCKET_ON_MESSAGE = 'COMMON_WEBSOCKET_ON_MESSAGE';
export const WEBSOCKET_ON_CLOSE = 'COMMON_WEBSOCKET_ON_CLOSE';
export const WEBSOCKET_ON_ERROR = 'COMMON_WEBSOCKET_ON_ERROR';
export const WEBSOCKET_ON_OPEN = 'COMMON_WEBSOCKET_ON_OPEN';

export const WEBSOCKET_LABOR_DEPLOY_PROCESS_MODULE = 'labor-deploy-process';
