export const DEPLOYS_GET_DEPLOY_LIST_BEGIN = 'DEPLOYS_GET_DEPLOY_LIST_BEGIN';
export const DEPLOYS_GET_DEPLOY_LIST_SUCCESS = 'DEPLOYS_GET_DEPLOY_LIST_SUCCESS';
export const DEPLOYS_GET_DEPLOY_LIST_FAILURE = 'DEPLOYS_GET_DEPLOY_LIST_FAILURE';

export const DEPLOYS_GET_DEPLOY_DETAIL_BEGIN = 'DEPLOYS_GET_DEPLOY_DETAIL_BEGIN';
export const DEPLOYS_GET_DEPLOY_DETAIL_SUCCESS = 'DEPLOYS_GET_DEPLOY_DETAIL_SUCCESS';
export const DEPLOYS_GET_DEPLOY_DETAIL_FAILURE = 'DEPLOYS_GET_DEPLOY_DETAIL_FAILURE';
