export const DEPLOYS_GET_DEPLOY_LIST_BEGIN = 'DEPLOYS_GET_DEPLOY_LIST_BEGIN';
export const DEPLOYS_GET_DEPLOY_LIST_SUCCESS = 'DEPLOYS_GET_DEPLOY_LIST_SUCCESS';
export const DEPLOYS_GET_DEPLOY_LIST_FAILURE = 'DEPLOYS_GET_DEPLOY_LIST_FAILURE';

export const DEPLOYS_GET_DEPLOY_DETAIL_BEGIN = 'DEPLOYS_GET_DEPLOY_DETAIL_BEGIN';
export const DEPLOYS_GET_DEPLOY_DETAIL_SUCCESS = 'DEPLOYS_GET_DEPLOY_DETAIL_SUCCESS';
export const DEPLOYS_GET_DEPLOY_DETAIL_FAILURE = 'DEPLOYS_GET_DEPLOY_DETAIL_FAILURE';

export const DEPLOYS_ADD_DEPLOY_BEGIN = 'DEPLOYS_ADD_DEPLOY_BEGIN';
export const DEPLOYS_ADD_DEPLOY_SUCCESS = 'DEPLOYS_ADD_DEPLOY_SUCCESS';
export const DEPLOYS_ADD_DEPLOY_FAILURE = 'DEPLOYS_ADD_DEPLOY_FAILURE';

export const DEPLOYS_DELETE_DEPLOY_BEGIN = 'DEPLOYS_DELETE_DEPLOY_BEGIN';
export const DEPLOYS_DELETE_DEPLOY_SUCCESS = 'DEPLOYS_DELETE_DEPLOY_SUCCESS';
export const DEPLOYS_DELETE_DEPLOY_FAILURE = 'DEPLOYS_DELETE_DEPLOY_FAILURE';
