export const DEPLOYS_GET_DEPLOY_LIST_BEGIN = 'DEPLOYS_GET_DEPLOY_LIST_BEGIN';
export const DEPLOYS_GET_DEPLOY_LIST_SUCCESS =
  'DEPLOYS_GET_DEPLOY_LIST_SUCCESS';
export const DEPLOYS_GET_DEPLOY_LIST_FAILURE =
  'DEPLOYS_GET_DEPLOY_LIST_FAILURE';

export const DEPLOYS_GET_DEPLOY_DETAIL_BEGIN =
  'DEPLOYS_GET_DEPLOY_DETAIL_BEGIN';
export const DEPLOYS_GET_DEPLOY_DETAIL_SUCCESS =
  'DEPLOYS_GET_DEPLOY_DETAIL_SUCCESS';
export const DEPLOYS_GET_DEPLOY_DETAIL_FAILURE =
  'DEPLOYS_GET_DEPLOY_DETAIL_FAILURE';

export const DEPLOYS_ADD_DEPLOY_BEGIN = 'DEPLOYS_ADD_DEPLOY_BEGIN';
export const DEPLOYS_ADD_DEPLOY_SUCCESS = 'DEPLOYS_ADD_DEPLOY_SUCCESS';
export const DEPLOYS_ADD_DEPLOY_FAILURE = 'DEPLOYS_ADD_DEPLOY_FAILURE';

export const DEPLOYS_START_DEPLOY_BEGIN = 'DEPLOYS_START_DEPLOY_BEGIN';
export const DEPLOYS_START_DEPLOY_SUCCESS = 'DEPLOYS_START_DEPLOY_SUCCESS';
export const DEPLOYS_START_DEPLOY_FAILURE = 'DEPLOYS_START_DEPLOY_FAILURE';

export const DEPLOYS_DELETE_DEPLOY_BEGIN = 'DEPLOYS_DELETE_DEPLOY_BEGIN';
export const DEPLOYS_DELETE_DEPLOY_SUCCESS = 'DEPLOYS_DELETE_DEPLOY_SUCCESS';
export const DEPLOYS_DELETE_DEPLOY_FAILURE = 'DEPLOYS_DELETE_DEPLOY_FAILURE';

export const DEPLOYS_ENQUEUE_DEPLOY_BEGIN = 'DEPLOYS_ENQUEUE_DEPLOY_BEGIN';
export const DEPLOYS_ENQUEUE_DEPLOY_SUCCESS = 'DEPLOYS_ENQUEUE_DEPLOY_SUCCESS';
export const DEPLOYS_ENQUEUE_DEPLOY_FAILURE = 'DEPLOYS_ENQUEUE_DEPLOY_FAILURE';

export const DEPLOYS_UPDATE_POD_VERSIONS_BEGIN = 'DEPLOYS_UPDATE_POD_VERSIONS_BEGIN';
export const DEPLOYS_UPDATE_POD_VERSIONS_SUCCESS = 'DEPLOYS_UPDATE_POD_VERSIONS_SUCCESS';
export const DEPLOYS_UPDATE_POD_VERSIONS_FAILURE = 'DEPLOYS_UPDATE_POD_VERSIONS_FAILURE';


export const DEPLOYS_CANCEL_DEPLOY_BEGIN =
  'DEPLOYS_CANCEL_DEPLOY_BEGIN';
export const DEPLOYS_CANCEL_DEPLOY_SUCCESS =
  'DEPLOYS_CANCEL_DEPLOY_SUCCESS';
export const DEPLOYS_CANCEL_DEPLOY_FAILURE =
  'DEPLOYS_CANCEL_DEPLOY_FAILURE';


export const DEPLOYS_MANUAL_POD_DEPLOY_BEGIN =
  'DEPLOYS_MANUAL_POD_DEPLOY_BEGIN';
export const DEPLOYS_MANUAL_POD_DEPLOY_SUCCESS =
  'DEPLOYS_MANUAL_POD_DEPLOY_SUCCESS';
export const DEPLOYS_MANUAL_POD_DEPLOY_FAILURE =
  'DEPLOYS_MANUAL_POD_DEPLOY_FAILURE';

export const DEPLOYS_ENQUEUE_POD_DEPLOY_BEGIN =
  'DEPLOYS_ENQUEUE_POD_DEPLOY_BEGIN';
export const DEPLOYS_ENQUEUE_POD_DEPLOY_SUCCESS =
  'DEPLOYS_ENQUEUE_POD_DEPLOY_SUCCESS';
export const DEPLOYS_ENQUEUE_POD_DEPLOY_FAILURE =
  'DEPLOYS_ENQUEUE_POD_DEPLOY_FAILURE';

export const DEPLOYS_CANCEL_POD_DEPLOY_BEGIN =
  'DEPLOYS_CANCEL_POD_DEPLOY_BEGIN';
export const DEPLOYS_CANCEL_POD_DEPLOY_SUCCESS =
  'DEPLOYS_CANCEL_POD_DEPLOY_SUCCESS';
export const DEPLOYS_CANCEL_POD_DEPLOY_FAILURE =
  'DEPLOYS_CANCEL_POD_DEPLOY_FAILURE';

export const DEPLOYS_WEBSOCKET_ON_MESSAGE = 'DEPLOYS_WEBSOCKET_ON_MESSAGE';
export const DEPLOYS_WEBSOCKET_ON_CLOSE = 'DEPLOYS_WEBSOCKET_ON_CLOSE';
export const DEPLOYS_WEBSOCKET_ON_ERROR = 'DEPLOYS_WEBSOCKET_ON_ERROR';
export const DEPLOYS_WEBSOCKET_ON_OPEN = 'DEPLOYS_WEBSOCKET_ON_OPEN';

export const DEPLOYS_LABOR_DEPLOY_PROCESS_MODULE = 'labor-deploy-process';
export const DEPLOYS_LABOR_DEPLOY_PROCESS_POD_TYPE = 'pod';
export const DEPLOYS_LABOR_DEPLOY_PROCESS_MAIN_TYPE = 'main';
