export const CI_GET_CI_STATUS_LIST_FAILURE = 'CI_GET_CI_STATUS_LIST_FAILURE';
export const CI_GET_CI_STATUS_LIST_BEGIN = 'CI_GET_CI_STATUS_LIST_BEGIN';
export const CI_GET_CI_STATUS_LIST_SUCCESS = 'CI_GET_CI_STATUS_LIST_SUCCESS';